### ISSUE TITLE
Building filter with existsFilter doesn't take 3th parameter

### ISSUE THREAD

**Issue by danielstaleiny** [danpaz/bodybuilder#54]
I am trying to build a filter for querying elastic search hosted on bonsai and when I am building my filter, results is not what it supposed to be. It seems that it doesn't take 3th parameter and it print
`"field": "field"` instead of `"field": "rate"`

`var body = new Bodybuilder()`
 `body.filter('exists', 'field', 'rate')`
 `body = body.build()`
 `console.log(JSON.stringify(body))`

Console log: 
`{"query":{"filtered":{"filter":{"exists":{"field":"field"}}}}}`
Expected result: 
`{"query":{"filtered":{"filter":{"exists":{"field":"rate"}}}}}`

I followed your documentation 
`var body = new Bodybuilder().filter('term', 'message', 'test').build()`
` body == {
   query: {
     filtered: {
       filter: {
         term: {
           message: 'test'
         }
       }
    }
   }
 }`

After some digging into your code it seems that method filter is using this: 
`export default function existsFilter(field) {
  return {
    exists: {
      field
    }
  }
}`

Instead of this: 
`export default function existsFilter(field, term) {
  return {
    exists: {
      [field]: term
    }
  }
}
`

I am running:
node version v5.7.1
npm 3.9.5
bodybuilder version:  1.15.1

**Comment by danpaz** [comment]
@danielstaleiny Thanks for the bug report. I think this was supposed to have been fixed in https://github.com/danpaz/bodybuilder/pull/41, can you double check you've got the latest version and try again? `npm install bodybuilder@latest`

**Comment by danielstaleiny** [comment]
I am quite sure I have this version 
`+-- bodybuilder@1.15.1`
`      | -- lodash@4.9.0`
but I still getting `"field": "field"` instead of `"field": "rate"`

I double check with npm install bodybuilder@latest as well.
Thank you for a quick reply.

**Comment by danpaz** [comment]
Looking more closely at your inputs, I think I see what's going on. The filter should be written as
`body.filter('exists', 'rate')`
instead of 
`body.filter('exists', 'field', 'rate')`

The `exists` filter clause is different from most others in that there is no search term, you simply pass the name of the field that must exist. 

I think this could be clarified with better documentation and examples for each filter/query/aggregation in bodybuilder. This has been on my mind but haven't had time to tackle it.

**Comment by danielstaleiny** [comment]
Thanks for clearing this out. 
I corrected it and now it is working as I expect it to.
